@echo off

rem FDBKl5ddcP3znhsipq7i4hoismaWS44C5cNi

rem echo ...............................................
rem echo setting C:\Users\%username% ...
set my_path_clone=C:\Users\%username%

rem echo ...............................................
rem echo cd'ing into %my_path_clone% ...
cd %my_path_clone%

rem echo ...............................................
rem echo checking %my_path_clone% ...
rem echo %cd%

rem echo passed 1 ..............

rem echo ...............................................
rem echo the classic token is: %zero%%one%%two%%three%%four%%five%%six%%seven%%eight%

echo ...............................................
set /p token="Enter token(It's okay, if you don't have the token): "

if not "%token%"=="" (
    echo Cloning repository with token: %token% ...
    git clone https://%token%@github.com/DafetiteOgaga/cucu_cupboard_repo.git
	set token=
) else (
    echo Cloning repository without token ...
    git clone https://github.com/DafetiteOgaga/cucu_cupboard_repo.git
)

endlocal
rem echo cloning cucu_cupboard_repo into %my_path_clone% ...
rem git clone https://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@github.com/DafetiteOgaga/cucu_cupboard_repo

rem git clone https://ghp_%token%@github.com/DafetiteOgaga/cucu_cupboard_installation.git

rem echo ...............................................
rem echo cd'ing into custom_commands_win ...
cd %my_path_clone%\cucu_cupboard_repo\custom_commands_win\

echo ...............................................
rem echo setting custom_commands_win path...
rem set custom_commands_win=%my_path_clone%\cucu_cupboard_repo\custom_commands_win
set custom_commands_win=%my_path_clone%\cucu_cupboard_repo\custom_commands_win

rem echo ...............................................
rem echo checking current directory ...
rem echo %cd%

rem echo ...............................................
rem echo checking custom_commands_win ...
rem echo %custom_commands_win%

rem echo ...............................................
rem echo viewing the content of config ...
rem type .\cucu_cupboard_repo\.git\config
rem type .\cucu_cupboard_installation\.git\config

rem echo passed 2 ..............

rem echo ...............................................
rem echo setting xbin_windows path...
set xbin_windows=%my_path_clone%\xbin_windows

rem echo ...............................................
rem echo creating xbin_windows in %my_path_clone% ...
mkdir %xbin_windows%

rem echo ...............................................
rem echo confirming that xbin_windows is created in %my_path_clone% ...
rem echo %xbin_windows%

echo ...............................................
echo setting environmental variable ...
setx PATH "%PATH%";%xbin_windows%

rem echo passed 3 ..............

rem echo ...............................................
rem echo cd'ing into xbin_windows ...
cd %xbin_windows%

rem echo ...............................................
rem echo checking xbin_windows ...
rem echo %xbin_windows%

rem echo passed 4 ..............

xcopy %custom_commands_win% . /e

rem echo passed 5 ..............