@echo off

cd C:\Users\pc\cucu_cupboard_repo\cucu_cupboard_venv_def_win\Scripts
echo ...............................................................
echo Activating virtual environment ...
call activate