@echo off

echo Running runserver_pull...
call runserver_pull.bat

echo Running runserver_activate_venv...
call runserver_activate_venv.bat

echo Running runserver_install_dependencies...
call runserver_install_dependencies.bat

echo Running runserer_copy...
call runserer_copy.bat

echo Running runserver_start_local_server...
call runserver_start_local_server.bat
echo ...............................................................
